[workspace]
resolver = "3"
members = ["engine", "client", "protocol", "server"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Quentin"]

[workspace.dependencies]
rand = "0.10.2"
catan = { path = "engine" }
catan-protocol = {path = "protocol"}
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
